apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app-container
        image: hyp2nos/crm-app # {"$imagepolicy": "flux-system:crm-app"}
        ports:
        - containerPort: 8080
