apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app
  namespace: flux-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-app
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
      - name: crm-app
        image: hyp2nos/crm-app:1.0.18 # {"$imagepolicy": "flux-system:crm-app"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
